export const data = [
    {
      id: 1,
      first_name: 'LODZ - LVIV',
      last_name: '115',
      email: '14h 30min',
      phone: 'General',
    },
    {
      id: 2,
      first_name: 'CAIRO - HURGADA',
      last_name: '178',
      email: '10h 30min',
      phone: 'Fast',
    },
    {
      id: 3,
      first_name: 'NEW YORK - WASHINGTON',
      last_name: '99',
      email: '9h 30min',
      phone: 'General',
    },
    {
      id: 4,
      first_name: 'ROME - NIZZA',
      last_name: '100',
      email: '4h 00min',
      phone: 'Fast',
    },
    {
      id: 5,
      first_name: 'DENVER - LOS ANGELES',
      last_name: '15',
      email: '18h 30min',
      phone: 'General',
    },
    {
      id: 6,
      first_name: 'BUENOS AIRES - KITO',
      last_name: '25',
      email: '10h 30min',
      phone: 'Fast',
    },
    {
      id: 7,
      first_name: 'PARIS - BERLIN',
      last_name: '23',
      email: '1h 30min',
      phone: 'Super Fast',
    },
    {
      id: 8,
      first_name: 'DUBLIN - LONDON',
      last_name: '11',
      email: '8h 30min',
      phone: 'General',
    },
    {
      id: 9,
      first_name: 'PRAGA - LEIPZIG',
      last_name: '5',
      email: '11h 15min',
      phone: 'General',
    },
    {
      id: 10,
      first_name: 'MADRID - TULON',
      last_name: '35',
      email: '1h 50min',
      phone: 'Super Fast',
    },
    {
      id: 11,
      first_name: 'MONAKO - ANTALYA',
      last_name: '55',
      email: '15h 30min',
      phone: 'General',
    },
    {
      id: 12,
      first_name: 'MIRA - REINZ',
      last_name: '11',
      email: '13h 30min',
      phone: 'Fast',
    },
    {
      id: 13,
      first_name: 'DUSSELDORF - BUHAREST',
      last_name: '18',
      email: '4h 30min',
      phone: 'Super Fast',
    },
    {
      id: 14,
      first_name: 'ANKARA - KAUNAS',
      last_name: '3',
      email: '13h 30min',
      phone: 'General',
    },
    {
      id: 15,
      first_name: 'RIGA - KIEV',
      last_name: '33',
      email: '9h 30min',
      phone: 'Fast',
    },
    
   
  ];